
name: Aktualizacja obrad komisji

on:
   schedule:
    - cron: '0 7 * * *'
   push:
     branches: main

permissions: write-all

jobs:
  render:
    name: Scraping
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install additional libs
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Scrape the data
        run: Rscript -e 'rmarkdown::render("R/scraping.R", output_file = "index.html")'
      - name: Commit results
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add index.html
          git commit -am "Ostatnia aktualizacja $(date)"
          git push origin main

